name: build-report
run-name: GPR Protokoll erstellen

on:
  schedule:
    - cron: '0 1 * 4-7 1'
  workflow_dispatch:

jobs:
  generate-pdf:
    name: Generate PDF File for Protocol
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine last Monday
        run: echo "CURRENT_PROTOCOL=$(date --date 'Monday - 7 days' --iso-8601)" >> "$GITHUB_ENV"
      
      - name: Build PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.CURRENT_PROTOCOL }}*/protokoll.tex
          glob_root_file: true
          work_in_root_file_dir: true
          latexmk_use_lualatex: true

      - name: Move generated PDF file and log
        run: |
          cp ${{ env.CURRENT_PROTOCOL }}*/protokoll.pdf protokoll.pdf
          cp ${{ env.CURRENT_PROTOCOL }}*/protokoll.log protokoll.log

      - uses: actions/upload-artifact@v3
        with:
          name: protocol
          path: |
            protokoll.pdf
            protokoll.log

  send-protocol:
    name: Send Protocol via E-Mail
    runs-on: ubuntu-latest
    needs: generate-pdf
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: protocol

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.MAIL_SERVER}}
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Versuchsprotokoll vom ${{ env.CURRENT_PROTOCOL }}
          # Required recipients' addresses:
          to: jan.eike.suchard@uni-oldenburg.de
          # Required sender full name (address can be skipped):
          from: Jan Eike Suchard
          # Optional plain body:
          body: Im Anhang befindet sich das aktuelle Versuchsprotokoll welches automatisch gebaut wurde.
          # Optional attachments:
          attachments: protokoll.pdf,protokoll.log
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: high